### ISSUE TITLE
what is benefit of using ( proguard-rules.pro ) and   implementation "androidx.core:core-ktx:1.10.0"

### ISSUE THREAD

**Issue by mazab99** [vicajilau/Drag-PDF#3]
there was a problem and when I removed them it works

**Comment by vicajilau** [comment]
I think ProGuard is something that would come when the project was created and has never been modified. R8 is more effective to reduce, obfuscate and optimise any flutter application. So It will be modified. 

On the other hand I would like to know more information about your error with "androidx.core:core-ktx:1.10.0" because as far as I can see it works. Could you give me more info? 

Thank you very much for your contribution to the project.
